// Generated by gencpp from file beginner_tutorials/WheelCommands.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_WHEELCOMMANDS_H
#define BEGINNER_TUTORIALS_MESSAGE_WHEELCOMMANDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct WheelCommands_
{
  typedef WheelCommands_<ContainerAllocator> Type;

  WheelCommands_()
    : CommandL(0.0)
    , CommandR(0.0)  {
    }
  WheelCommands_(const ContainerAllocator& _alloc)
    : CommandL(0.0)
    , CommandR(0.0)  {
  (void)_alloc;
    }



   typedef float _CommandL_type;
  _CommandL_type CommandL;

   typedef float _CommandR_type;
  _CommandR_type CommandR;





  typedef boost::shared_ptr< ::beginner_tutorials::WheelCommands_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::WheelCommands_<ContainerAllocator> const> ConstPtr;

}; // struct WheelCommands_

typedef ::beginner_tutorials::WheelCommands_<std::allocator<void> > WheelCommands;

typedef boost::shared_ptr< ::beginner_tutorials::WheelCommands > WheelCommandsPtr;
typedef boost::shared_ptr< ::beginner_tutorials::WheelCommands const> WheelCommandsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::WheelCommands_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::WheelCommands_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::WheelCommands_<ContainerAllocator1> & lhs, const ::beginner_tutorials::WheelCommands_<ContainerAllocator2> & rhs)
{
  return lhs.CommandL == rhs.CommandL &&
    lhs.CommandR == rhs.CommandR;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::WheelCommands_<ContainerAllocator1> & lhs, const ::beginner_tutorials::WheelCommands_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::WheelCommands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::WheelCommands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::WheelCommands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::WheelCommands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::WheelCommands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::WheelCommands_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::WheelCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da8262406bdbe1e606838ce0ded8f1bb";
  }

  static const char* value(const ::beginner_tutorials::WheelCommands_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda8262406bdbe1e6ULL;
  static const uint64_t static_value2 = 0x06838ce0ded8f1bbULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::WheelCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/WheelCommands";
  }

  static const char* value(const ::beginner_tutorials::WheelCommands_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::WheelCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 CommandL\n"
"float32 CommandR\n"
;
  }

  static const char* value(const ::beginner_tutorials::WheelCommands_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::WheelCommands_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.CommandL);
      stream.next(m.CommandR);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelCommands_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::WheelCommands_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::WheelCommands_<ContainerAllocator>& v)
  {
    s << indent << "CommandL: ";
    Printer<float>::stream(s, indent + "  ", v.CommandL);
    s << indent << "CommandR: ";
    Printer<float>::stream(s, indent + "  ", v.CommandR);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_WHEELCOMMANDS_H
